from pydantic import BaseModel
from typing import List, Optional

# What the user sends from the frontend
class ProcessRequest(BaseModel):
    description: str

# Individual step in the business workflow generated by Claude
class WorkflowStep(BaseModel):
    id: int
    title: str
    actor: str  # Who does this step? (e.g., "Employee", "Manager", "HR")
    description: str
    next_step_ids: List[int]

# The complete structured JSON object we expect back from Claude
class WorkflowAnalysis(BaseModel):
    process_name: str
    summary: str
    steps: List[WorkflowStep]
    potential_bottlenecks: List[str]
    ai_automation_suggestions: List[str]